version: '3.8'

services:
  backend:
    # 构建配置
    build:
      context: ./bookkeeper-app  # Dockerfile 所在的目录
      dockerfile: Dockerfile
    # 服务名称，用于服务间通信
    container_name: bookkeeper_backend
    # 重启策略：除非手动停止，否则容器总会重启
    restart: unless-stopped
    volumes:
      - db-data:/data  # 我们需要修改Go代码，让它从/data/simple_ledger.db读写
    # 端口映射
    ports:
      - "9999:8080"
    # 健康检查（可选，但推荐）
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    # 网络配置
    networks:
      - app-network

  # 前端服务定义
  frontend:
    build:
      context: ./frontend-reborn
      dockerfile: Dockerfile
    container_name: bookkeeper_frontend
    restart: unless-stopped
    # 端口映射
    # 将宿主机的 5173 端口映射到容器的 80 端口
    ports:
      - "9988:80"
    # 依赖关系
    # 确保后端服务启动之后再启动前端服务
    depends_on:
      backend:
        condition: service_healthy # 依赖于后端的健康检查结果
    networks:
      - app-network

# 定义网络
networks:
  app-network:
    driver: bridge

# 定义卷（用于数据库持久化）
volumes:
  db-data: