
services:
  # 后端服务定义
  backend:
    build:
      context: ./bookkeeper-app
      dockerfile: Dockerfile
    container_name: bookkeeper_backend
    restart: unless-stopped
    # 【新增】设置环境变量，告诉 Go 程序在容器内使用这个路径
    environment:
      - DB_PATH=/data/simple_ledger.db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY} # 从环境变量中读取 JWT 密钥
    # 使用命名卷（named volume）来持久化数据
    volumes:
      - db-data:/data
    ports:
      - "9999:8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  # 前端服务定义
  frontend:
    build:
      context: ./frontend-reborn
      dockerfile: Dockerfile
    container_name: bookkeeper_frontend
    restart: unless-stopped
    ports:
      - "9988:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

# 定义网络
networks:
  app-network:
    driver: bridge

# 定义命名卷
volumes:
  db-data: